version: "3.9"

services:
    #################### mysql ####################
    mysql:
        expose:
            - ${DB_PORT:-3306}

    #################### clickhouse ####################
    clickhouse:
        expose:
            - "8123"   # HTTP port
            - "9000"   # Native client port
            - "9009"   # TCP port
            - "9100"   # gRPC

    #################### redis ####################
    redis:
        expose:
            - ${REDIS_PORT:-6379}

    ################### rabbitmq ##################
    rabbitmq:
        expose:
            - "5672"
        ports:
            - ${RABBIT_MANAGEMENT:-}:15672
